### ISSUE TITLE
Python Code

### ISSUE THREAD

**Issue by Bill-Ren** [webis-de/cikm20-web-page-segmentation-revisited-evaluation-framework-and-dataset#2]
Thanks for your great work, I would like to ask if there is a python code for the dataset evaluation process as I have not learned R language.

**Comment by johanneskiesel** [comment]
Thanks! But we provide code only in R.

If you want to read the data structures, however, we use the "Simple Features" standard: https://en.wikipedia.org/wiki/Simple_Features

From what I understand, one Python implementation of this standard is the GDAL Python package, so you should be able to read the segmentations with this package: https://pypi.org/project/GDAL/

**Comment by Bill-Ren** [comment]
Thank you for your patience in answering, I will try it now, thank you again!
